spring:
  datasource:
    url: jdbc:mysql://localhost:3306/luongtd
    username: root
    password: 123456a@
    driver-class: com.mysql.cj.jdbc.Driver
    connection-timeout: 20000
    minimum-idle: 1
    maximum-pool-size: 256
    idle-timeout: 10000
    max-lifetime: 2000
    pool-name: Job-Extend
    data-source-properties: v$session.program=Job-Extend
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 1993
encrypt:
  encrypt-password: Y



