spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: 123456a@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 1994
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


